name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: clang-tidy check
      uses: muxee/clang-tidy-action@0.0.1-rc1
    - uses: actions/checkout@v1 
    - name: Compile
      run: mkdir bin && cd bin && ../odin build ../src/* && cd ..
    - uses: actions/upload-artifact@master
      with:
        name: linux-native-build
        path: bin
