name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install clang
      run: sudo apt install clang
    - name: Install llvm
      run: sudo apt install llvm 
    - uses: actions/checkout@v1 
    - name: Compile
      run: mkdir bin && cd bin && ../odin build ../src/* && cd ..
    - uses: actions/upload-artifact@master
      with:
        name: linux-native-build
        path: bin
